# THIS IS ONLY EXAMPLE
# change needed paths
$validator: ./validator/global_config.schema.yaml

regulatory_domain: CZ
internet_interface: wlan0
timeout_external_bb_scan_sec: 5
paths:
  # These config keys are not included in result config,
  hostapd:
    # in this folder will be folder with cloned repository and binaries
    # (create empty folder if not sure, it will be build automatically)
    hostapd_build_folder: ../../tools/hostapd
    hostapd_mana_build_folder: ../../tools/hostapd_mana
  openssl:
    # vulnerable OpenSSL builds for hostapd (e.g. openssl-1.0.2f)
    openssl_vuln_build_folder: ../../tools/openssl_vuln
  dragonslayer:
    # dragonslayer folder (!dragonslayer has subfolder dragonslayer)
    dragonslayer_folder: ../../tools/dragonslayer
  dragondrain:
    dragondrain_folder: ../../tools/dragondrain-and-time
  ath_masker: ../../tools/ath_masker
  WPA3_SAE_DoS_Research_Suite: ../../tools/WPA3-SAE-DoS-Research-Suite
actors:
  conn_table: ./example_whitebox_table.csv
  ignore_interfaces: [ wlan0 ]
nm_exclude_actors: false
install_req: true
compile_external: true
save_log: true