file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/test_data DESTINATION ${CMAKE_CURRENT_BINARY_DIR})

add_subdirectory(test_helpers)
add_subdirectory(scan)
add_subdirectory(logger)
add_subdirectory(config)
add_subdirectory(observer)
add_subdirectory(setup)
add_subdirectory(ex_program)
add_subdirectory(attacks)
add_subdirectory(system)
add_subdirectory(integration)
add_subdirectory(suite)
add_subdirectory(overview)
