ctrl_interface=/var/run/hostapd
driver=nl80211

ssid=OpenWrtd
channel=40

hw_mode=a
#ieee80211n=1
ieee80211w=2

sae_pwe=2
auth_algs=1
wpa=2
wpa_key_mgmt=SAE
rsn_pairwise=CCMP
sae_password=password123

