driver=nl80211
ssid=wpa3_tester_sta_info
hw_mode=g
auth_algs=1
wpa=2
ieee80211n=1
ieee80211w=1
wpa_key_mgmt=SAE WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=password123
sae_password=password123
channel=6
