$schema: "https://json-schema.org/draft/2020-12/schema"
title: Shared test run configuration properties
type: object

properties:
  delete_old:
    type: boolean

  test_report:
    type: boolean

  rewrite:
    oneOf:
      - type: boolean
        const: false
      - type: string
        enum: [ errors, all ]

  compile_external:
    type: boolean

  install_req:
    type: boolean

  save_log:
    type: boolean
    description: Save logs from log() function to run_folder/logger/tester.log
