driver=nl80211
ssid=OpenWrt_2_4GHz
hw_mode=g
channel=6
ieee80211n=1

wpa=2
wpa_key_mgmt=WPA-PSK
wpa_passphrase=password123
#correct password (to only check WPA3-> WPA2 downgrade)
#TODO hashcat is dump in password formating for cracking
rsn_pairwise=CCMP

ieee80211w=1
mana_loud=1
#mana_wpaout=mana_handshakes.hccapx