ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
    ssid="SafeNet"
    key_mgmt=SAE
    sae_password="password123"
    ieee80211w=2
    proto=RSN
    pairwise=CCMP
    group=CCMP
    priority=5
}

network={
    ssid="WrongNet"
    key_mgmt=SAE
    sae_password="password123"
    ieee80211w=2
    proto=RSN
    pairwise=CCMP
    group=CCMP
    priority=10
}
