ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
    ssid="SafeNet"
    key_mgmt=WPA-EAP
    eap=PWD
    identity="user"
    password="password123"
    scan_freq=2412
    freq_list=2412
    priority=50
}

network={
    ssid="WrongNet"
    key_mgmt=WPA-EAP
    eap=PWD
    identity="user"
    password="password123"
    scan_freq=2462
    freq_list=2462
    priority=10
}