# name | git-url | EXTRA_CFLAGS | tag  (empty tag = latest commit)
rtw88|https://github.com/lwfinger/rtw88|-DCONFIG_RTW88_DEBUGFS -DCONFIG_RTW88_DEBUG|22/4/24
8821cu|https://github.com/morrownr/8821cu-20210916||bda65aac150d2cde0df9603206eec23a6f3b77c4
rtl8852au|https://github.com/WimLee115/rtl8852au-build|-DCONFIG_RTW89_DEBUGFS -DCONFIG_RTW89_8852AU -DCONFIG_RTW89_DEBUG|v1.17.0
