driver=nl80211
ssid=test_owe
hw_mode=g
channel=6

#wpa=2
#wpa_key_mgmt=OWE
#wpa_passphrase=wrong_password
#rsn_pairwise=CCMP
#wpa_pairwise=CCMP
wpa=0

ieee80211w=0
macaddr_acl=0
#mana_loud=1
#mana_credout=/tmp/wpa.creds
