auth_algs=1
channel= 11  #for minimim interfacesbetween channel
driver=nl80211
hw_mode=g
ieee80211n=1
ieee80211w=2
rsn_pairwise=CCMP
sae_password=password123
ssid=test_mc_mitm
wpa=2
wpa_key_mgmt=SAE
wpa_passphrase=password123
