ctrl_interface=/var/run/wpa_supplicant
update_config=1
country=CZ

network={
    ssid="SafeNet"
    proto=RSN
    key_mgmt=SAE
    pairwise=CCMP
    group=CCMP
    ieee80211w=2
    sae_password="password123"
    priority=5
}

#network={
#    ssid="WrongNet"
#    proto=RSN
#    key_mgmt=SAE
#    pairwise=CCMP
#    group=CCMP
#    ieee80211w=2
#    sae_password="password123"
#    priority=2
#}